# Generated by Django 3.1.2 on 2024-05-28 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleBoleta',
            fields=[
                ('idDetalle', models.AutoField(primary_key=True, serialize=False)),
                ('nombreDetalle', models.CharField(max_length=100)),
                ('montoDetalle', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('comentario', models.CharField(max_length=100)),
                ('idAgenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agenda')),
                ('nFolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.boleta')),
            ],
        ),
    ]
