# Generated by Django 3.1.2 on 2024-05-28 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_detalleboleta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleBoleta',
        ),
    ]
