# Generated by Django 5.0.6 on 2024-05-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_detalleboleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocustom',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
