# Generated by Django 5.0.6 on 2024-06-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_taller_descripcion_taller_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='subModelo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
