# Generated by Django 5.0.6 on 2024-06-10 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_vehiculo_submodelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='fechaAgenda',
        ),
    ]
