# Generated by Django 5.0.6 on 2024-06-10 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_agenda_fechaagenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='cliente',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
