# Generated by Django 5.0.6 on 2024-06-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_agenda_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taller',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
