# Generated by Django 4.1 on 2025-10-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_servicio_tallerservicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='direccion',
            field=models.CharField(max_length=500),
        ),
    ]
