# Generated by Django 4.1 on 2025-10-20 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_taller_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='idTipoAgenda',
        ),
        migrations.AddField(
            model_name='agenda',
            name='idServicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.servicio'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TipoAgenda',
        ),
    ]
