# Generated by Django 4.1 on 2025-10-21 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_agenda_idtipoagenda_agenda_idservicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('idFormaPago', models.AutoField(primary_key=True, serialize=False)),
                ('nombreFormaPago', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='reportepago',
            name='idFormaPago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.formapago'),
        ),
    ]
