# Generated by Django 4.1 on 2025-10-21 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_formapago_reportepago_idformapago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formapago',
            name='descripcion',
        ),
    ]
