# Generated by Django 4.1 on 2025-10-22 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_formapago_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionTaller',
            fields=[
                ('idCalificacion', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField(choices=[(1, 'Mala'), (2, 'Regular'), (3, 'Buena'), (4, 'Muy Buena'), (5, 'Excelente')])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('idTaller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.taller')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
