# Generated by Django 4.1 on 2025-10-27 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_calificaciontaller'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritoTaller',
            fields=[
                ('idFav', models.AutoField(primary_key=True, serialize=False)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.taller')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'taller')},
            },
        ),
    ]
