# Generated by Django 4.1 on 2025-11-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_preferenciasusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocustom',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
